export const FETCH_FOODS = "FETCH_FOODS"
export const ADD_TO_ORDER = "ADD_TO_ORDER"
export const CURRENT_USER = "CURRENT_USER"
export const NEW_USER = "NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const USER_OBJECT = "USER_OBJECT"
